---
# tasks file for ansible-atop

- name: Install atop packages on Debian/Ubuntu systems
  become: true
  apt:
    name: "{{ atop_packages }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default(omit) }}"
    install_recommends: false
  when: ansible_os_family == "Debian"
  tags:
    - atop

- name: Enable EPEL repository on RHEL-based systems
  become: true
  package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"
  tags:
    - atop

- name: Install atop packages on RHEL/CentOS/AlmaLinux/Rocky Linux systems
  become: true
  package:
    name: "{{ atop_packages }}"
    state: present
  when: ansible_os_family == "RedHat"
  tags:
    - atop
