---
# Multi-platform testing scenario - Tests against all supported OS versions
driver:
  name: docker
platforms:
  # Ubuntu 20.04 LTS (Focal Fossa)
  - name: instance-ubuntu-20
    image: ubuntu:20.04
    pre_build_image: true
    command: /bin/bash -c "while true; do sleep 30; done"
    tmpfs:
      - /run
      - /tmp
  # Ubuntu 22.04 LTS (Jammy Jellyfish)
  - name: instance-ubuntu-22
    image: ubuntu:22.04
    pre_build_image: true
    command: /bin/bash -c "while true; do sleep 30; done"
    tmpfs:
      - /run
      - /tmp
  # Ubuntu 24.04 LTS (Noble Numbat)
  - name: instance-ubuntu-24
    image: ubuntu:24.04
    pre_build_image: true
    command: /bin/bash -c "while true; do sleep 30; done"
    tmpfs:
      - /run
      - /tmp
  # Debian 12 (Bookworm)
  - name: instance-debian-12
    image: debian:bookworm
    pre_build_image: true
    command: /bin/bash -c "while true; do sleep 30; done"
    tmpfs:
      - /run
      - /tmp
  # AlmaLinux 9
  - name: instance-almalinux-9
    image: almalinux:9
    pre_build_image: true
    command: /bin/bash -c "while true; do sleep 30; done"
    tmpfs:
      - /run
      - /tmp
  # Rocky Linux 9
  - name: instance-rocky-9
    image: rockylinux:9
    pre_build_image: true
    command: /bin/bash -c "while true; do sleep 30; done"
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance-ubuntu-20:
        ansible_distribution: Ubuntu
        ansible_distribution_release: focal
        ansible_distribution_major_version: "20"
        ansible_os_family: Debian
        ansible_connection: docker
        ansible_user: root
        ansible_become: false
      instance-ubuntu-22:
        ansible_distribution: Ubuntu
        ansible_distribution_release: jammy
        ansible_distribution_major_version: "22"
        ansible_os_family: Debian
        ansible_connection: docker
        ansible_user: root
        ansible_become: false
      instance-ubuntu-24:
        ansible_distribution: Ubuntu
        ansible_distribution_release: noble
        ansible_distribution_major_version: "24"
        ansible_os_family: Debian
        ansible_connection: docker
        ansible_user: root
        ansible_become: false
      instance-debian-12:
        ansible_distribution: Debian
        ansible_distribution_release: bookworm
        ansible_distribution_major_version: "12"
        ansible_os_family: Debian
        ansible_connection: docker
        ansible_user: root
        ansible_become: false
      instance-almalinux-9:
        ansible_distribution: AlmaLinux
        ansible_distribution_release: ""
        ansible_distribution_major_version: "9"
        ansible_os_family: RedHat
        ansible_connection: docker
        ansible_user: root
        ansible_become: false
      instance-rocky-9:
        ansible_distribution: Rocky
        ansible_distribution_release: ""
        ansible_distribution_major_version: "9"
        ansible_os_family: RedHat
        ansible_connection: docker
        ansible_user: root
        ansible_become: false
verifier:
  name: ansible